CREATE DATABASE IF NOT EXISTS jushi DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE jushi;

CREATE TABLE IF NOT EXISTS sys_user (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  real_name VARCHAR(64) DEFAULT NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'user',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS deploy_instance (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  deployment_name VARCHAR(128) NOT NULL UNIQUE,
  gpu_vendor VARCHAR(32) NOT NULL,
  gpu_type VARCHAR(64) NOT NULL,
  gpu_count INT NOT NULL DEFAULT 1,
  deploy_type VARCHAR(64) NOT NULL,
  creator VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'created',
  node_ports JSON DEFAULT NULL,
  log_path VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS port_block_rule (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  port INT NOT NULL UNIQUE,
  remark VARCHAR(255) DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operation_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  operation_type VARCHAR(64) NOT NULL,
  operator VARCHAR(64) DEFAULT NULL,
  operator_ip VARCHAR(64) DEFAULT NULL,
  target_type VARCHAR(64) DEFAULT NULL,
  target_name VARCHAR(128) DEFAULT NULL,
  request_payload JSON DEFAULT NULL,
  response_payload JSON DEFAULT NULL,
  http_status_code INT DEFAULT NULL,
  is_success TINYINT(1) NOT NULL DEFAULT 0,
  error_message TEXT DEFAULT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alert_event (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  alert_type VARCHAR(64) NOT NULL,
  alert_level VARCHAR(32) NOT NULL,
  title VARCHAR(128) NOT NULL,
  message TEXT DEFAULT NULL,
  source VARCHAR(64) DEFAULT NULL,
  target_name VARCHAR(128) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME DEFAULT NULL,
  resolver VARCHAR(64) DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS resource_snapshot (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  snapshot_type VARCHAR(64) NOT NULL,
  payload JSON NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
